### ISSUE TITLE
Jquery chosen doesn't work on mobile device

### ISSUE THREAD

**Issue by antoniopuero** [storebrand/storebrand.ny#17]
This plugin doesn't work (doesn't applies its view and its behavior to the select element). To reproduce it, choose the phone emulation in chrom dev tools and test storebrand.ny page

**Comment by nilsel** [comment]
Thanks for the report. UA-sniffing is a path I don't like to revisit, but browser-vendors might have grown up a bit since last time. Detecting if a UA is mobile or not in a reliablie and future-proof way is the hardest problem in computer science at the moment ;)
Maybe a combination of checking viewport-size, touch-support (or other mobile-only features) and UA-sniffing. More research is needed.
