### ISSUE TITLE
Spring cleaning 2016

### ISSUE THREAD

**Issue by nilsel** [storebrand/storebrand.ny#33]
I went thru the project and did some cleanup. This is mostly for a tidier repo and a better development-experience. No layout/design changes.

### Reasons, because:
- JS source directory was littered with vendor-scripts. We should not add third-party code here.
- Generated JS/CSS was hard to identify, generated files should be separate in a folder, not alongside the source files.
- Some scripts did stuff that was not expected from the filename (ex. stb-page-padding.js)
- $(document).ready is all over the place (todo: fix)
- Production bundle should be "stb-all.min.css" and "stb-all.min.js"
- Remove unused/obsolete steps from gruntfile

### TODO/wanted:
- Should we generate different bundles for open/logged in? Seems like use-cases differ wildly. Many clients can also get away with just the CSS file.
- Add webmanual to private NPM for easy consumption and versioning
- SVG: separate svg-playground for icons and illustrations
- Separate out any scripts that rely on $(document).ready?
- major: refactor to Riot.js for a more modular approach (scoped css, template+js in same file, custom tags). This will probably need it's own branch.

This work is being done in a separate branch: https://github.com/storebrand/storebrand.ny/tree/feature/spring-cleaning-2016

### Changes so far:

**Gruntfile:**
- concat-step removed, we only need uglify-task for JS
- sourcemaps fixed for JS+LESS
- show info in CLI if no task argument specified
- removed obsolete gzip-step

**Directory structure:**
- js+less source now lives i src/js and src/less
- All generated/compiled files (*.html, less/*, js/*) is now built/copied to public/ and served from that directory

**Remove vendor-scripts from repo:**
- spin.js via NPM
- moment via NPM
- jquery.eqheight via NPM
- bootstrap via NPM (less+js)
- jquery.hotkeys via NPM
- spin.js via NPM + config in src/stb-spinjs-presets.js

**JS**
- move TOC-list code (from stb-page-padding.js) to separate file src/stb-toc-list.js
- Medallia file removed
- Analyze class-code moved (from stb-page-padding.js) to src/stb-analyze.js

**package.json**
- lock down all versions to explicit version so we don't get patch differences

**Other:**
- remove bower dependency 👊 

request for comments: @stbbzt @eivindingebrigtsen @anderslosvik

**Comment by stbbzt** [comment]
All the suggestions make sense to me. While I wasn't that unhappy with stb-page-padding.js, it should be just as understandable to someone entering the project as to those who have been working on it, so the fact that you found it confusing is proof enough that we should probably extract some parts of the page-padding to other functional descriptions. 

I'd prefer as few branches as possible, so if you can merge this into/as the main one, we'll continue working from there immediately. We should document on Wiki how one can use and contribute to the Web manual when NPM is required. 

Regarding open/logged in, I don't know what the best way forward is. We're looking at re-using the open pages on Enonic as logged in pages, with some added/replaced contents. In that case, the Web manual used should be the same in both contexts. For the various clients that are parts of Personportalen today, they should be rewritten, in some cases from scratch, in order to look good and perform well, so in those cases we should also use the same Web manual. Then there are the many clients that could just get a mark-up update and use only the CSS ... If we can create a minimalist Web manual that contains only a minor subset of the Web manual, it would be good. I'm not exactly sure what that subset should be, though. As long as we have a fairly tide codebase, it should be easy to decide and create a suitable package through grunt when we have an actual use case. 

Finally; maybe we can also move to Bootstrap 3.3.6 now, as part of the spring cleaning? :)

**Comment by nilsel** [comment]
Updated bootstrap to 3.3.6 ⚡

**Comment by nilsel** [comment]
Closing this, it's not really a issue. I'll create a development-wishlist or something similar in the wiki.
Some things I really want:
- publish package as npm module
- different bundles for different usage
- Riot.js PoC
